apiVersion: v1
kind: Secret
metadata:
  name: ims-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongodb:27017"
  MONGO_DB: "incident_management"
  INCIDENT_COLLECTION: "incidents"
  SESSION_COLLECTION: "sessions"
